### ISSUE TITLE
#1172 broke company integration

### ISSUE THREAD

**Issue by arybczak** [haskell/haskell-mode#1440] opened 2016-10-20 20:55 UTC
#1172 makes company (and presumably also auto-complete) not work at all, because it overwrites `completion-at-point-functions` [here](https://github.com/haskell/haskell-mode/pull/1172/files#diff-7477b53a55071572a5b29b786ff3d054R787).

I don't know about auto-complete, but company-mode with company-dabbrev-code and company-etags backends provides great auto-completion facilities (and in case of company-etags ability to jump to source with C-w directly from the list of completions) and currently it's got silently suppressed by a piece of code that offers completion of keywords/pragmas and simple declarations alone.
#1172 should've been implemented as either auto-complete or company backend (as was already mentioned by @cocreature in #215) instead of hard-coding it into haskell-mode as it effectively hides company/auto-complete functionality from users.

At the very least, if the completion code is kept in its current state, at least make overwriting `completion-at-point-functions` optional and disable it by default. But really it should be made into company backend so it composes with other backends.

**Comment by geraldus** [comment] 2016-10-21 09:05
@arybczak can you create and maintain backends you talking about both for `company` and `AC`?

**Comment by arybczak** [comment] 2016-10-21 10:00
I can't, because my elisp writing skills are close to none.

But having these as company/ac backends is just the end goal, the main problem is actually that current behaviour prevents company from working (and I don't know why exactly that happens either, all I know is that commenting out the statement I pointed to solves the problem).

**Comment by gracjan** [comment] 2016-11-08 08:26
Is there somewhere in the vast internet a guide how to properly implement completions in Emacs? It sounds more involved than it should be.

I agreed with cocreature that we should leave dabbrev alone and I thought we already do skip that. Aren't we?

If it goes about me we can just support conditional dependency on company and autocomplete. The issue is of course work required to build those integrations and then maintain them.

Any volunteers?

**Comment by arybczak** [comment] 2016-11-08 09:24
> Is there somewhere in the vast internet a guide how to properly implement completions in Emacs? It sounds more involved than it should be.

It looks like writing company backends is quite straightforward: https://github.com/company-mode/company-mode/wiki/Writing-backends

> I agreed with cocreature that we should leave dabbrev alone and I thought we already do skip that. Aren't we?

I'm not sure, but for the record, company offers company-dabbrev backend, which works well.

BTW, I later found out that company supposedly integrates with completion-at-point-functions (by company-capf backend), but for some reason it doesn't, i.e. when haskell-mode sets completion-at-point-functions, other backends stop working. I'm not sure whether it's a bug in company or the implementation of haskell-mode's completion function.

**Comment by gracjan** [comment] 2016-11-08 13:59
I tried to understand company mode integration and I do not see how this is different than `completion-at-point-functions`. company mode invokes backends in order, the first one that returns non-nil is the one selected as source for completions. Same mechanism as `completion-at-point-functions`. I do not understand the need for existence of company mode other than a GUI.

**Comment by arybczak** [comment] 2016-11-08 19:25
You can combine backends together, e.g. (company-dabbrev-code company-etags) will give you completions from both backends.

**Comment by gracjan** [comment] 2016-11-11 13:47
@arybczak: what is the value of your `company-backends` variable?

**Comment by arybczak** [comment] 2016-11-11 14:29
```
(company-c-headers company-bbdb company-nxml company-css company-eclim company-semantic company-xcode company-cmake company-capf company-files
                   (company-dabbrev-code company-gtags company-etags company-keywords)
                   company-oddmuse company-dabbrev)
```

**Comment by arybczak** [comment] 2016-11-11 14:34
@gracjan 

I also have

```
(eval-after-load 'company-etags
      '(progn
         (add-to-list 'company-etags-modes 'haskell-mode)))
```

To enable etags completion in haskell-mode.

and for haskell-mode I just use defaults:

```
;; enable haskell-mode
(defconst haskell-mode-directory "~/.emacs.d/haskell-mode/")
(add-to-list 'load-path haskell-mode-directory)
(require 'haskell-mode-autoloads)
(add-to-list 'Info-default-directory-list haskell-mode-directory)
```

You can see the whole configuration [here](https://github.com/arybczak/emacs-config/blob/master/init.el) if that helps.

**Comment by gracjan** [comment] 2016-11-11 14:34
Looks like you have `company-capf` in the list on the first level. This means `company-mode` will call backends in turn `company-c-headers` ... up to `company-capf`. Then `company-capf` will return something using `completions-at-point-functions` and there the process stops. If your `company-backend` looked like this:

```
(company-c-headers ... company-files
                   (company-capf company-dabbrev-code ... company-dabbrev)
```

Then all backends from the inner list would be called and a set-union of results would be made. I guess this is what you want, right?

**Comment by arybczak** [comment] 2016-11-11 15:08
Hmm, yeah, putting company-capf inside the group works, but it's baffling as if completion-at-point-functions doesn't return anything, company-capf should presumably let subsequent backends do the job, but that is not the case. Maybe it's actually a bug in company-capf :/

**Comment by gracjan** [comment] 2016-11-11 15:13
Maybe. I'm closing this one.

**Closed by gracjan** 2016-11-11 15:13 UTC
