### ISSUE TITLE
Annoying indentation behaviour when declaring data types

### ISSUE THREAD

**Issue by jstolarek** [haskell/haskell-mode#1081] opened 2016-01-14 17:34 UTC
Say I have this code:
```haskell
foo = undefinedX
```
where `X` is the cursor position. If I press Enter twice the cursor ends up at the beginning of a new line:
```haskell
foo = undefined

X
```
This is all fine. Now consider a similar situation with data type declaration:
```haskell
data Foo = Bar
         | BazX
```
Now pressing Enter twice yields:
```haskell
data Foo = Bar
         | Baz

           X
```
This is mostly annoying. If I press Enter twice after a data constructor declaration then I almost certainly want to start some new declaration and thus expect the cursor to be placed at the beginning of a new line. So the rule should be: when pressing enter on a line that contains only whitespace characters place the cursor at the beginning of a new line. Note also that current behaviour is inconsistent:

```haskell
data Foo = BarX
```
Pressing Enter here will place the cursor at the beginning of a new line, but I would really expect it to be placed under `=`:
```haskell
data Foo = Bar
         X
```
Only when I press enter for the second time I want the cursor to be placed at the beginning of a new line.

**Comment by gracjan** [comment] 2016-01-14 19:28
I'm really grateful for these reports. Keep those coming. We will fix as
soon as possible. Thanks again.

**Comment by jstolarek** [comment] 2016-01-15 09:12
I thought a bit more about this and I think that pressing Enter in this situation:

```haskell
data Foo = BarX
```
should yield:
```haskell
data Foo = Bar
               X
```
that is assume by default that I will be writing arguments of `Bar`. In this example this doesn't look good, but it seems to make sense in general. For example:
```haskell
data Foo = Bar Int Char
               X
```
It would be nice if entering a vertical bar in the setting above was detected and indentation corrected automatically to:
```haskell
data Foo = Bar Int Char
         | X
```
Note the space already inserted after the `|`. Also, in this setting:
```haskell
data Foo = Bar Int Char
               X
```
I would expect that repeatedly pressing Tab will cycle me between four indentations:
```haskell
data Foo = Bar Int Char
X        Y Z   Q
```
Currently I am cycled only between `X` and `Z`.

**Comment by gracjan** [comment] 2016-01-15 09:26
Electric behavior for bar comma semicolon is in the plans. Hard to say when
we will have energy to do this.

**Comment by gracjan** [comment] 2016-01-23 13:16
Note that `haskell-indent` behaves the same. Logic what should happen after ENTER is pressed is here:

https://github.com/haskell/haskell-mode/blob/master/haskell-indentation.el#L188

**Comment by gracjan** [comment] 2016-01-27 11:50
This is a duplicate of #747.

**Closed by gracjan** 2016-01-27 11:50 UTC
