### ISSUE TITLE
Haskell indentation weirdly re-indents lines after sp-kill-sexp

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#1031] opened 2015-12-23 10:29 UTC
I don't know why this happens, quick serch doens't show any relevant hook or advices in `haskell-indentation.hs`. However, when you call `sp-kill-sexp` (from Smartparens) with `haskell-indentation-mode` enabled, current line is weirdly re-indented after deletion of the sexp. So, every time you need to re-indent it.

**Comment by mrkkrp** [comment] 2015-12-23 10:41
It also happens after `sp-kill-hybrid-sexp` and who knows what else. Ahhh…

**Comment by mrkkrp** [comment] 2015-12-23 10:53
There must be a way to disable re-indenting after this sort of operations.

**Comment by gracjan** [comment] 2015-12-23 11:36
Can you add a test case to `tests/haskell-indentation-tests.el`?

**Comment by mrkkrp** [comment] 2015-12-23 13:34
To add tests for this, we first need to understand why exactly this happens. I don't think installing `smartparens` package only to test these cases is the right thing to do. Most probably we're seeing something that has nothing to do with `smartparens`, but just somehow is visible in this case.

**Comment by gracjan** [comment] 2015-12-23 14:18
If the test could test that 'something' without smartparens then that is
even better in my book.

**Comment by bergey** [comment] 2015-12-23 15:44
After killing, `smartparens` calls `sp--cleanup-after-kill` which calls `sp--indent-region`.  You can turn this off (for haskell) with `(add-to-list 'sp-no-reindent-after-kill-modes 'haskell-mode)`

I suppose this makes sense in languages that delimit blocks with characters rather than indentation.  The other values of `sp-no-reindent-after-kill-modes` seem to confirm this.

**Comment by gracjan** [comment] 2015-12-23 16:31
In this case this issue is a duplicate of #796. Closing as dupe.

**Closed by gracjan** 2015-12-23 16:31 UTC

**Comment by gracjan** [comment] 2015-12-23 16:32
Noted the need of indent-region in #1032.

**Comment by mrkkrp** [comment] 2015-12-23 17:09
Perfect, thanks guys!
