### ISSUE TITLE
Let the enter create a new line despite the indentation errors

### ISSUE THREAD

**Issue by vagifverdi** [haskell/haskell-mode#905] opened 2015-10-01 17:39 UTC
I see a lot of errors when hitting the enter. They are all different, ususally saying Expecting (something here)

The error is not a bug deal. But the fact that it stops me from simply createing a new line is.

While you guys are trying to figure out numerous test cases to fix all indentation issues, could you please just make it create a new line regardless if it encountered any error?

As of now haskell-mode is completely broken and unusable because of it.

**Comment by gracjan** [comment] 2015-10-01 17:48
The omitted part is very interesting. What tokens are reported?

**Comment by vagifverdi** [comment] 2015-10-01 18:25
All kind of tokens
not just one but all kinds of them. And almost on every line. It is ridiculous. I simply cannot enter a new line almost anywhere in my code. I resorted to copy pasting lines when i need to enter a new one.

And this is just when i need to prep a new guy and teach him haskell and the tools. So embarrassing.

Here are just some of the errors:

"Expecting ->" (usually after quiasiquotes like [st|blah blah|]

"Illigal token: ;" also after quasiquotes, but this time html in the quasiquotes, and it does have some ; in there.

"Expecting of" after quasiquotes with sql statements

"Illigal token: value" after quasiquotes with sql statements, butinterestingly they do not contain any word "value"

"Illigal token: in" after quasiquotes with sql statements that contain " in "

Anyway, i do not mind those errors. But can we make it to create a new line if i press enter? regardless of the error?

**Comment by gracjan** [comment] 2015-10-01 19:50
So QuasiQuotes are the culprit. Good to know.

We support QuasiQuotes by treating them as 'special strings'. Most of
haskell mode knows how to handle those, haskell-indentation needs to be
toughts. It is not a hard task.

Are you able to look into this yourself and help us implementing missing
feature?

**Comment by ivan-m** [comment] 2015-10-02 04:24
As a work around, you can use `C-q C-j` to force inserting a newline.

**Comment by gracjan** [comment] 2015-10-02 12:11
Closing as a duplicate of #894.

**Closed by gracjan** 2015-10-02 12:11 UTC
