### ISSUE TITLE
Stepped indentation with haskell-indentation-mode and yasnippets

### ISSUE THREAD

**Issue by eigengrau** [haskell/haskell-mode#719] opened 2015-06-11 19:28 UTC
When haskell-indent-mode is active, using  `ghc-insert-template-or-signature` to expand a class instance stub, or expanding from a yasnippet keyword, produces odd indentation. It looks as if the layout rule is applied after every line.

```
instance Num Token where
    x + y = _body
            x - y = _body
                    x * y = _body
                            …
```

**Comment by eigengrau** [comment] 2015-06-11 20:00
I have noticed that when using `haskell-indentation-mode` instead, `ghc-insert-template-or-signature` yields the correct results, while yasnippet expansion (courtesy of haskell-snippets) still yields the stepping.

**Comment by gracjan** [comment] 2015-06-11 20:09
Haskell-indent-mode is no longer supported I'm afraid.

**Comment by eigengrau** [comment] 2015-06-11 20:16
Ah, okay, thanks. So this is for `haskell-indentation-mode` (no electric indent mode active). Yasnippets issue?

```
x = case var of
  cond -> value
          
          otherwise -> other
```

**Comment by gracjan** [comment] 2015-06-12 06:31
yassnippets have their own github issues page, I guess it is better to report there.

**Comment by LukeHoersten** [comment] 2015-06-12 14:06
I'm seeing the same problem as you with `haskell-indentation-mode` and `haskell-snippets`.

Yasnippets really has no control over how the buffer treats indentation as the snippet goes in. All the `haskell-snippets` go in with spaces for indentation as well so I don't think `tab` characters are causing indentation to run or anything. You can see how straightforward the snippet is here:
https://github.com/haskell/haskell-snippets/blob/master/snippets/haskell-mode/case

My feeling at this point is that it's something to do with `haskell-indentation-mode` or `yasnippet` itself outside of the control of the snippet.

**Comment by npostavs** [comment] 2015-12-03 02:09
Hi, yasnippet dev here. It looks like there exists a [`case` snippet in yasnippet-snippets][1] which is where the snippet collection comes from in a typical install (MELPA).  The yasnippet-snippets one lacks the `# expand-env: ((yas-indent-line 'fixed))` which haskell-mode's has. Perhaps this is the reason for the problem?

Regardless, I suggest you ask @AndreaCrotti to update the haskell snippets in his repository, or else remove them entirely.

[1]: https://github.com/AndreaCrotti/yasnippet-snippets/blob/56a9f62c38196cb56115569bbb4361898162c42e/haskell-mode/case

**Comment by AndreaCrotti** [comment] 2015-12-03 13:00
Hi @npostavs yes well I can definitively update them, but just to be clear only the snippets in haskell mode that would have indentation need that right?
I think it's only *class* and *case* from what I can see so far, is that right?

**Comment by AndreaCrotti** [comment] 2015-12-03 13:04
I tried and this works

https://github.com/AndreaCrotti/yasnippet-snippets/pull/107

if that's all we need I'll merge that @npostavs @eigengrau 
If anyone else could confirm that snippet works fine it would be great

**Comment by xuzhao9** [comment] 2016-01-29 04:30
Still have this problem on haskell-mode-20160128.621 and yasnippet-20160122.1056.
My snippet that triggers this problem see here:
https://pastebin.com/DQLzy2rg

**Comment by gracjan** [comment] 2016-01-29 06:27
@xuzhao9: Can you help us finding the root cause of this? Please do:

- [ ] restart Emacs
- [ ] try yassnippet with `haskell-indent` instead of `haskell-indentation`
- [ ] disable `electric-indent-mode`

Please report back what you found, thanks.

**Comment by xuzhao9** [comment] 2016-02-01 03:09
Hello, I have restarted emacs.
1. The result of using haskell-indent instead of haskell-indentation is slightly different but still problematic.
See: http://pastebin.com/pAZnPiw7.
2. Disabling electrc-indent-mode does not help either.

**Comment by jarmitage** [comment] 2016-07-08 16:38
Hi,

I am also having this problem:

1. Type snippet shortcut
2. Use TAB or RET to expand
3. Haskell code indents

Any ideas of even a quick workaround?

Thanks

**Comment by npostavs** [comment] 2016-07-08 16:54
Is this still with the `case` snippet or other snippets? Perhaps it's best to disable yasnippet auto indenting for haskell mode:

```elisp
(defun set-yasnippet-fixed-indent ()
  (setq-local yas-indent-line 'fixed))
(add-hook 'haskell-mode #'set-yasnippet-fixed-indent)
```

**Comment by jarmitage** [comment] 2016-07-08 17:04
This is with other snippets. That doesn't seem to work either I'm afraid. Currently I am just disabling `haskell-indentation-mode` (manually, see: #90)

**Comment by npostavs** [comment] 2016-07-08 17:10
> This is with other snippets.

Please show a concrete example so that others might have a chance of replicating your problem.

**Comment by jarmitage** [comment] 2016-07-08 17:24
It's slightly complex, as I'm using [Tidal](http://github.com/tidalcycles/Tidal) which is built on Haskell and uses the same indentation mode.

An example snippet for Tidal would be:

```
# -*- mode: snippet -*-
# name: sustain 
# key: #s
# --
# sustain "$0"
```

And an example of using this in Tidal would be:

```
d1 $ sound "bd" # sustain "0.5"
; or
d1 $ sound "bd"
    # sustain "0.5"
```

In either case, currently using the `#s` snippet causes indentation after triggering.

If you want I can try to see if the problem is exactly the same in Haskell, but you'll have to provide an example as I'm not a Haskell programmer.

**Comment by npostavs** [comment] 2016-07-08 20:50
I'm neither a Haskell nor Tidal programmer :)

I had the wrong hook variable name [in my suggestion above](https://github.com/haskell/haskell-mode/issues/719#issuecomment-231412853), edited now. After fixing that problem, it seems to work.

Started emacs with `emacs -Q -L haskell-mode -L Tidal -L yasnippet -l haskell -l tidal.el -l yasnippet.el -f yas-global-mode`

Evaluate 
```elisp
(progn (defun set-yasnippet-fixed-indent ()
         (setq-local yas-indent-line 'fixed))
       (add-hook 'haskell-mode-hook #'set-yasnippet-fixed-indent))
```
`M-x tidal-mode`
`C-u M-x yas-new-snippet`
Put
```
# -*- mode: snippet -*-
# name: sustain 
# key: #s
# --
# sustain "$0"
```
`C-c C-l RET` to load snippet
`C-x b RET` switch back to `*scratch*`
`M-<` `C-w` delete original text
Put
```
d1 $ sound "bd"
#s
```
Hit `<tab>`, now I have
```
d1 $ sound "bd"
# sustain ""
```

**Comment by jarmitage** [comment] 2016-07-08 21:18
Wow amazing, can't wait to try this later! Thank you

**Comment by jarmitage** [comment] 2016-07-09 09:50
That works for the case where the snippet is on a new line, but not when the snippet is in an existing line, which is much more common in Tidal. Any ideas for extending your function to include snippets in existing lines?

**Comment by npostavs** [comment] 2016-07-09 11:37
I tried `d1 $ sound "bd" #s` and pressing `<tab>` gave me `d1 $ sound "bd" # sustain ""` with no change to indentation. Can you give an example where it doesn't work?

**Comment by jarmitage** [comment] 2016-07-09 14:41
That's strange. Are you working with `haskell-indentation-mode` enabled too? I will have another go and check back here...

**Comment by npostavs** [comment] 2016-07-09 14:45
> Are you working with `haskell-indentation-mode` enabled too?

Yes, according to `<f1> v haskell-indentation-mode RET` (this is all using same `emacs -Q -L haskell-mode -L Tidal ...` setup detailed above).

**Comment by gracjan** [comment] 2016-07-19 11:39
Looks to me that this issue is more about yasnippets than haskell-indentation. Therefore closing.

Thanks for participation!

**Closed by gracjan** 2016-07-19 11:39 UTC
Labels: indentation
