### ISSUE TITLE
With latest version, cannot change haskell-indentation

### ISSUE THREAD

**Issue by jwiegley** [haskell/haskell-mode#906] opened 2015-10-01 19:55 UTC
I'm using haskell-indentation.el at version c77a08a612652a33f0f9403feb9e73d3de2a4e5b, and I've configured the following variables:

``` elisp
 '(haskell-indent-spaces 4)
 '(haskell-indentation-ifte-offset 4)
 '(haskell-indentation-layout-offset 4)
 '(haskell-indentation-left-offset 4)
 '(haskell-indentation-starter-offset 4)
 '(haskell-indentation-where-post-offset 4)
 '(haskell-indentation-where-pre-offset 4)
```

However, after restarting Emacs and loading a Haskell file, all indentations are somehow back to 2.

**Comment by jwiegley** [comment] 2015-10-01 19:58
This does not happen with 47d90c83f101596be92a44d98b9ebf8a6089efc0, so the issue seems to be somewhere between those two.

**Comment by emmanueltouzery** [comment] 2015-10-02 14:23
i'm having the same issue, came here to open the bug, glad i'm not the only one affected.

**Comment by emmanueltouzery** [comment] 2015-10-15 06:12
no answer? :-(

**Comment by gracjan** [comment] 2015-10-21 15:42
@emmanueltouzery: Somebody needs to sit down in debug this. I've read the code and there is nothing that jumps on me that should cause this behavior.

We need a test case for all these settings.

**Comment by emmanueltouzery** [comment] 2015-10-21 15:49
@gracjan did you reproduce the issue? For me sadly i'll never find the time to fix the issue, no way.

**Comment by gracjan** [comment] 2015-10-21 15:51
Just trying to reproduce... so far it works for me. @emmanueltouzery: do you use MELPA or MELPA-STABLE version of haskell-mode? Or maybe git version?

**Comment by emmanueltouzery** [comment] 2015-10-21 15:54
I know very little about the whole thing. Using spacemacs stable and it hides the whole thing from me (luckily for me).

Let's say if I have a do, press enter, i get 2 spaces. Used to be correctly 4.

**Comment by gracjan** [comment] 2015-10-21 16:02
If you do `M-x cusstomize-group RET haskell` and the find options named "Haskell Indentation Left Offset" and change that to 4, will that work?

There are some other variables that are also set to 2 by default. If it works with this one you should changed also the other ones to have consistent behavior.

I've also filled in #952: "Unify haskell-indentation defcustoms into one variable". @emmanueltouzery I know time is limited but this is pretty simple search and replace job. Can you do #952 for us, @emmanueltouzery?

**Comment by emmanueltouzery** [comment] 2015-10-21 16:21
here's what I found out. If I the `customize-group` (as I already did at the time I first set this up), I see the values set at 2. Although it's at 4 in my config file. I change to 4, IT WORKS. Until I restart emacs. Note that I say "Apply and Save". And it saves the settings (but since I already changed them I only see whitespace changes in my config file).

In other words maybe try to change it, save, and restart emacs. I think then you'll see the problem.

**Comment by emmanueltouzery** [comment] 2015-10-21 16:21
unlikely I can do bug #952 :-(

**Comment by emmanueltouzery** [comment] 2015-10-21 16:22
I mean related to #952 I think it might be a bad idea. Will write there.

**Comment by emmanueltouzery** [comment] 2015-10-21 16:29
with regards to my version of `haskell-mode`. I went in `M-x list-packages` and here's what I see related to haskell:

    haskell-emacs      20151004.1030 available  melpa      Write emacs extensions in haskell
    haskell-emacs-base 20150714.859  available  melpa      Haskell functions from Prelude
    haskell-emacs-text 20150713.716  available  melpa      Haskell functions from Data.Text

**Comment by gracjan** [comment] 2015-10-26 19:48
I've tried to reproduce this issue, including saving customizations and restarting Emacs. Everything works like a charm.

**Comment by emmanueltouzery** [comment] 2015-10-27 05:35
Could this be a version problem? I have listed my version earlier in the
bug. Do you have the same version?

**Comment by ivan-m** [comment] 2015-10-27 12:20
@emmanueltouzery you didn't actually state the version from what I could find.  And even if it was a bug in a previous version of haskell-mode, from what @gracjan has said with his testing it seems it no longer exists in the current version so it's fixed.

Are you able to update your version to a newer one?

**Comment by emmanueltouzery** [comment] 2015-10-27 12:24
here I listed the version: https://github.com/haskell/haskell-mode/issues/906#issuecomment-149952713

20151018.225 i'll try if i can update, but 2015.10.18 doesn't seem that old...

**Comment by emmanueltouzery** [comment] 2015-10-27 12:28
@jwiegley can you still reproduce yourself? thank you!

**Comment by emmanueltouzery** [comment] 2015-10-28 19:13
I have upgraded `haskell-mode` and now I get `progn: Symbol's function definition is void: haskell-indentation-disable-show-indentations`...

I guess something is wrong with my configuration. And probably a bug report is not the right canal if that's the case. My dot files are otherwise there, but I guess it's probably correct to close the bug: https://github.com/emmanueltouzery/dotspacemacs

**Comment by PierreR** [comment] 2015-10-28 19:27
@emmanueltouzery Just in case you don't use `spacemacs` do you ? Because the master branch is currently broken because of this change (the fix is merged in develop and should be release in master soon)

**Comment by gracjan** [comment] 2015-10-28 19:27
This symbol has been removed. You seem to have a reference to it in your
.emacs file, please remove it from there, too.

**Comment by emmanueltouzery** [comment] 2015-10-28 19:32
Yes I use spacemacs... I didn't see a bug there. I don't use that symbol in my .spacemacs.
I'll stick with my "old" haskell-mode version until the next spacemacs release... It has bad indentation but mostly works...

**Comment by gracjan** [comment] 2015-10-28 19:36
Oh boy, what is spacemacs doing with these symbols?

Which spacemacs commit fixes this issue?

**Comment by gracjan** [comment] 2015-10-28 19:48
I've reported this issue to spacemacs: https://github.com/syl20bnr/spacemacs/issues/3580

**Comment by PierreR** [comment] 2015-10-28 19:48
My own commit 
https://github.com/syl20bnr/spacemacs/commit/5473d441d42b671c5cc5feae21fcfc08184b77f9 :-)

**Comment by PierreR** [comment] 2015-10-28 19:50
They already know about the problem and I know they are planning to integrate the bugfix (just removing the call to these symbols) in master quite soon.

**Comment by PierreR** [comment] 2015-10-28 19:53
Here is the link to the PR:
https://github.com/syl20bnr/spacemacs/pull/3527

**Comment by gracjan** [comment] 2015-10-28 19:55
Well, I've added an issue so it is not forgotten.

**Comment by emmanueltouzery** [comment] 2015-11-02 07:30
a new version of spacemacs was now released, I tried again but I still see the issue. Still 2 indents despite my config file. I now have haskell-mode 20151101.709.
I guess my config is at fault, or maybe but presumably not spacemacs.  I guess I'll try to debug it.
My config is there otherwise, I think it has nothing special:
https://github.com/emmanueltouzery/dotspacemacs

**Comment by emmanueltouzery** [comment] 2015-11-03 13:07
Ok I think it can be closed (can't close it myself as I'm not the author). I think it's not caused by `haskell-mode`. If I put the `custom-set-variables` in my `dotspacemacs/config` function in my `.spacemacs` it works. If I put it just at the end of my `.spacemacs` as is the default... It doesn't work. I can't find anything in my .spacemacs that would overwrite the values. But I have to assume `haskell-mode` has no part in this problem.

**Comment by gracjan** [comment] 2015-11-03 13:29
@syl20bnr: Can you confirm/deny that spacemacs may be at play here?

**Comment by bgamari** [comment] 2015-11-12 10:22
@syl20bnr, ping; I believe I am also seeing the behavior observed by @emmanueltouzery .

**Closed** 2015-12-26 17:41 UTC
