### ISSUE TITLE
Shelling out to `which` for executable paths

### ISSUE THREAD

**Issue by ocramz** [haskell/haskell-mode#1358] opened 2016-06-10 21:37 UTC
I need to switch GHC versions, and can't seem to find anywhere a menu that lets me set the path for `ghc` and related tools. I did use it once though, but I can't recall the incantation.

In general, wouldn't it be simpler if the mode called `which`, at least on Unix-based systems, for retrieving the system-wide path to commands such as `ghc`, `ghci`, `stack` etc. ?

Thank you

**Comment by chrisbarrett** [comment] 2016-06-10 23:18
Perhaps surprisingly, `which` isn't portable across *nixes. haskell-mode uses Emacs' builtin functions for doing this, which will work correctly if you have Emacs' exec-path set correctly. Given that a go? :)

**Comment by gracjan** [comment] 2016-06-11 08:17
Emacs finds executables by using `exec-path`. If what is executed goes via some shell then `PATH` environment variable gets its say where shell looks for other executables.

See #975. (I'm closing this one as dupe of #975).

**Closed by gracjan** 2016-06-11 08:17 UTC

**Comment by fice-t** [comment] 2016-06-11 23:25
You also may want to look into the `haskell-process-path-` variables.

**Comment by ocramz** [comment] 2016-06-12 09:35
@fice-t `exec-path` is the most robust way of doing. I don't have a way to assess which path variable takes priority, but `M-x customize-variable`ing  `exec-path` worked.
