### ISSUE TITLE
Infinite "Contacting host: stable.melpa.org:80"

### ISSUE THREAD

**Issue by nbro** [haskell/haskell-mode#1490] opened 2017-03-03 21:12 UTC
I'm trying to install this mode. I added the following code (as explained in the README)

```
(require 'package)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-archives
   (quote
    (("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa-stable" . "http://stable.melpa.org/packages/")))))
```

to the file `~/emacs`. Then I re-open Emacs and I type `M-x package-refresh-contents`, and the following appears in a buffer:

```
Contacting host: elpa.gnu.org:80
Contacting host: stable.melpa.org:80
```

and it seems that it never terminates. 

I'm not very familiar in general with Emacs but I would like to try it with this mode.

**Comment by ivan-m** [comment] 2017-03-05 23:14
This has nothing to do with Haskell mode and is more to do with Emacs not being able to connect to the internet to get package descriptions (let alone package).

As a start: are you behind a proxy?

**Comment by nbro** [comment] 2017-03-05 23:43
@ivan-m I don't think I'm behind a proxy server. (I'm using Passive FTP mode).

**Comment by ivan-m** [comment] 2017-03-05 23:47
Well, let's try debugging the connection.

Does `M-x eww` let you browse to a website?

**Comment by nbro** [comment] 2017-03-05 23:50
@ivan-m Yes, it lets me do it.

**Comment by ivan-m** [comment] 2017-03-05 23:53
Which OS are you using?

And just to clarify: _which_ file did you put this in? Do you mean `~/.emacs`?

**Comment by ivan-m** [comment] 2017-03-05 23:55
Also, you say you're using Passive FTP mode; how exactly? AFAIK, FTP isn't used for this at all...

**Comment by nbro** [comment] 2017-03-05 23:57
@ivan-m I'm using macOS Sierra (10.12.3). I put that content in the file `~/.emacs`, yes.

Here's what I meant when I'm using Passive FTP mode:

<img width="663" alt="screen shot 2017-03-06 at 00 56 39" src="https://cloud.githubusercontent.com/assets/9349000/23592889/dc6a7330-0207-11e7-9dcb-adb03e4042d0.png">

**Comment by ivan-m** [comment] 2017-03-06 00:02
OK, I've got that box ticked on my Mac as well (but I haven't upgraded to Sierra yet).

Which version of Emacs are you using? (If it has package.el I'm guessing it's not the one that ships with MacOS.)

Maybe just double-check your network settings in whichever browser you use to make sure you don't have any settings there.

Is this a corporate network (which might have some kind of filtering somewhere)?

Possibly try with Emacs with no init file (`emacs -Q`) and see if `package-list-packages` works there using the default settings.

**Comment by nbro** [comment] 2017-03-06 00:13
@ivan-m I'm not using Emacs (which possibly came with the OS). I'm using one that I installed as an app. 

I'm using GNU Emacs 24.5.1. 

I use Chrome usually. The proxy settings there lead to the system proxy settings.

`package-list-packages` works, it's `package-refresh-packages` that doesn't seem to work...

**Comment by ivan-m** [comment] 2017-03-06 00:17
How did you install it? From where? (In case you're using a tweaked build that changes something.)

No other network specific settings in Chrome?

`package-list-packages` (which is an alias for `list-packages`) calls `package-refresh-contents`  (via `package-menu-refresh`) unless you specify the optional `NO-FETCH` variable.

**Comment by nbro** [comment] 2017-03-06 00:23
@ivan-m Solved, I think, at least now it highlights the Haskell code, which before wasn't doing it. Tomorrow I will play more with it. 

I basically searched for this `haskell-mode` library from the list returned by `package-list-packages` and then I click `[Install]` on the buffer that appear when I click on the item of the list corresponding to `haskell-mode`. 

Anyway, I installed Emacs some time ago, not sure from where.

**Comment by ivan-m** [comment] 2017-03-06 00:25
Yes, that's what you want to do.

Try and upgrade if you can; 25.1 is now out which has a few new goodies (including concurrent connections for package.el to make installations faster).  Homebrew has it, with a flag to add extra integrations.

But if this is solved, please close the issue.

**Comment by nbro** [comment] 2017-03-06 15:06
@ivan-m I've installed the new version of Emacs using brew (in my case) from https://www.gnu.org/software/emacs/download.html#macos and now when I tried to do the same thing, i.e. placing the lisp code above on `.emacs` and running `package-refresh-contents`, I got the famous "Failed to download `melpa' archive.". I tried then to install `haskell-mode` by going to `package-list-packages` (as I did with my previous version of Emacs), and it worked.

I think this issue should remained opened, since it's not actually explainable the behaviour I'm having, and it should be solved or at least explained why this is happening.

**Comment by ivan-m** [comment] 2017-03-07 04:40
Let's just clarify the steps that you're doing here and try and make it reproducible.

1. Start emacs with `emacs -Q`
2. Add the following to the `*scratch*` buffer that appears:
```elisp
(require 'package)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-archives
   (quote
    (("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa-stable" . "http://stable.melpa.org/packages/")))))
```
3. `M-x eval-buffer`
4. `M-x package-refresh-contents`

This for me also errors out with melpa-stable.  However, if I go to `M-x package-list-packages` then all the melpa-stable packages are there.

Doing this all again but with `M-x toggle-debug-on-error` after step 3 gives me the following stack-trace:

```elisp
Debugger entered--Lisp error: (error "package.el is not yet initialized!")
```

So it looks like the README is missing a `(package-initialize)` at the end of the snippet to put into `.emacs`.

@gracjan ^^

**Comment by ivan-m** [comment] 2017-03-07 04:42
(Btw, using `list-packages` avoids this issue as it must call `(package-initialize)` :p  But since that's needed on future starts to actually get the packages loaded...)

**Closed** 2017-03-12 17:14 UTC

**Comment by countvajhula** [comment] 2020-12-08 04:25
Just reporting here FAI that I had a similar issue, where it was hanging while attempting to connect to `stable.melpa.org:443`. Using @ivan-m 's `emacs -Q` debug code showed that `stable.melpa.org:80` was working. It proved to be an invalid config in my `~/.ssh/config` file that I'd recently added that was causing the https connection to fail. Removing it solved the issue.
