### ISSUE TITLE
Overly aggressive indenting after recent Emacs update

### ISSUE THREAD

**Issue by giogadi** [haskell/haskell-mode#377] opened 2014-11-23 17:00 UTC
Howdy,

I recently updated to the latest version of Emacs on Homebrew (using OSX Yosemite):

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/emacs.rb

Suddenly, whenever I go to a new line using simple-indent-mode the editor *always* adds a 4-space indent, even in simple cases like:

```haskell
foo :: Int
    foo = 1 -- auto-indent inserted here by haskell-mode
```

This behavior persisted even after completely nuking my emacs installation and starting over. Has anyone else experienced this issue?

**Comment by gracjan** [comment] 2015-01-30 17:00
Note that `electric-indent-inhibit` works only on non-empty lines or when cursor in not in the first column. So `electric-indent-inhibit` does not really fix the 'newline-and-indent' aggresive behavior of `haskell-simple-indent`:

     (unless (and electric-indent-inhibit
            (not at-newline)
        (indent-according-to-mode))))))

**Comment by gracjan** [comment] 2015-02-27 13:27
@purcell: I still get 'newline-and-indent'  despite your changes in https://github.com/haskell/haskell-mode/commit/99658ce11e08b8f0825a17247bc84336b6a4cd8c

**Comment by ivan-m** [comment] 2015-09-13 01:12
I think we need to do something similar in `haskell-cabal-mode` as well, as electric-indent can do weird indentation there as well.

**Comment by slpopejoy** [comment] 2015-09-13 01:15
Given the bad support for `electric-indent-inhibit` noted in https://github.com/haskell/haskell-mode/issues/377#issuecomment-72233321 I propose haskell-mode go for a full shutdown of electric indent a la https://github.com/haskell/haskell-mode/issues/377#issuecomment-64126148

**Comment by gracjan** [comment] 2015-09-13 10:21
Radical. Can we do some more research about this?

Electric mode has a black list of modes when it does not activate. It might
be better to add Haskell-mode to that list.

**Comment by slpopejoy** [comment] 2015-09-13 23:17
Honestly I'm a little surprised that the various indentations *do not* use electric, since that seems to work fine for c, java, perl etc. While on this topic, I wonder why haskell-mode doesn't leverage `semantic` to parse source files ... I worked pretty heavily on java emacs stuff in another life and semantic kinda rules.

**Comment by gracjan** [comment] 2015-09-14 05:39
Electric seems to work best for languages with a unique, well defined
indentation point derived from curly braces or parentheses. Haskell usually
has multiple choices how a line should be indented with different semantics
so a programmer needs to choose which semantics he wants.

What exactly does 'semantic' buy in this case? Honest question, I've never
used it.

**Comment by purcell** [comment] 2015-09-14 07:26
[Semantic](https://www.gnu.org/software/emacs/manual/html_node/emacs/Semantic.html) is pretty huge, and `java-mode` doesn't use it afaik -- I don't think it's really a building block for major modes. There are languages with more complicated syntax than haskell which Emacs managed to indent robustly. An example would be `ruby-mode`, which in its latest incarnation is built on the new `smie` indent engine thanks to the work of @dgutov. I'm not aware of an idiomatic way of building bounce-indent major modes, which I think is the key issue here.

**Comment by gracjan** [comment] 2015-09-14 07:56
Is there a well known open source project that depends on semantic?

**Comment by slpopejoy** [comment] 2015-09-16 01:00
While `java-mode` doesn't use semantic, `jdee` does which is more like `haskell-mode` in that it offers completion, ant integration, maybe maven now too for all I know. Via `semantic` it's able to offer nice things like incremental parsing, completion in as-yet-uncompiled code, etc. 

My experience back then (circa 2003) was semantic was very fast and has a great API for use within an IDE-like mode. 

The problem is more that Haskell doesn't offer a BNF afaict. With a BNF you fire up `Wisent` and you're done![ The comments in Lexer.x indicate it was produced from regexes, presumably in the Haskell report. Someone would probably have to handcode a Bison-style input for Wisent ...

... or follow the semantic docs in writing a regex-based tag generator, using the Haskell report. This could be OK too in that it would at least centralize parsing code in one place. Apparently this disables incremental parsing though.

references:
JDEE: https://github.com/jdee-emacs/jdee
Semantic docs: http://cedet.sourceforge.net/addlang.shtml
GHC Parser docs: https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/Parser 
Haskell 2010 syntax: https://www.haskell.org/onlinereport/haskell2010/haskellch10.html
https://www.reddit.com/r/haskell/comments/2ig8ml/where_can_i_find_the_complete_bnf_syntax_of/
http://sourceforge.net/p/cedet/mailman/message/21667834/
http://stackoverflow.com/a/11511916/4015221

**Comment by gracjan** [comment] 2015-10-18 10:56
About agressive indenting.

One. `electric-indent` blacklist all haskell indentation modes:

```
(defvar electric-indent-functions-without-reindent
  '(indent-relative indent-to-left-margin indent-relative-maybe
    py-indent-line coffee-indent-line org-indent-line yaml-indent-line
    haskell-indentation-indent-line haskell-indent-cycle haskell-simple-indent
    yaml-indent-line))
```

Two. `haskell-indentation-mode` provides its own `haskell-indentation-newline-and-indent` function that is directly bound to `RET` and as if electric indent was always on.

Anyway this issue got offtopic, lets close it. If somebody experiences staricase problem again please report a new issue. Thanks.

**Closed by gracjan** 2015-10-18 10:56 UTC
