### ISSUE TITLE
Parse Error inside QuasiQuotes

### ISSUE THREAD

**Issue by ericnething** [haskell/haskell-mode#907] opened 2015-10-01 20:38 UTC
I am using haskell-mode version 20150920.858 from melpa. I updated a few days ago. The code below gives me the error `Illegal Token: =`
~~~haskell
messageField :: Monad m => RenderMessage (HandlerSite m) FormMessage => Field m Text
messageField = Field
  { fieldParse = parseHelper $ Right
  , fieldView = \theId name attrs val isReq -> [whamlet|
$newline never
<input id="#{theId}" name="#{name}" maxlength="140" type="text" value="#{either id id val}" :isReq:required  *{attrs}>
  |]
  , fieldEnctype = UrlEncoded
  }
~~~

It is the `<input>` line that is causing the problem. Strangely, if I remove the quotations from `value="#{either id id val}"`, the error goes away. Nothing inside the QuasiQuotes should be parsed.

**Comment by ivan-m** [comment] 2015-10-02 04:23
This is a duplicate of #894

**Closed** 2015-10-02 12:07 UTC
