### ISSUE TITLE
Error when I try to input string

### ISSUE THREAD

**Issue by YouerSu** [haskell/haskell-mode#1672] opened 2019-08-09 08:55 UTC
When I tried to input the string "[]" above the {- (the order is important),It stucked and took away lots of memory.

like that:
{-
then,try to input "[" above it
"["
{-
It will stuck when I press the button

**Comment by purcell** [comment] 2019-11-10 21:34
Duplicate of https://github.com/haskell/haskell-mode/issues/1577

**Closed by purcell** 2019-11-10 21:34 UTC
