### ISSUE TITLE
Interactive buffer inhibits scrolling

### ISSUE THREAD

**Issue by shanemikel** [haskell/haskell-mode#1435] opened 2016-10-13 07:02 UTC
I've noticed recently that (only when cursor is on the current prompt line) scrolling in the interactive buffer won't allow moving the prompt off-screen.

That is, once it gets to the edge, the buffer annoyingly jumps back.

**Comment by fice-t** [comment] 2016-10-21 23:40
I can't seem to reproduce this. Are you using the latest version? Can you give a specific recipe to produce the issue?

Though I have noticed similar interactive buffer jumping in the past, when closing windows.

**Comment by gracjan** [comment] 2016-11-11 15:24
Closing due to lack of information. Reopen if necessary.

**Closed by gracjan** 2016-11-11 15:24 UTC
