### ISSUE TITLE
installation error 'electric-pair-default-inhibit' 

### ISSUE THREAD

**Issue by presci** [haskell/haskell-mode#1683] opened 2019-11-14 07:17 UTC
Getting error while installing haskell-mode. emacs version = 26.1. Debian OS
`
In toplevel form:
haskell-mode.el:1213:1:Error: the function 'electric-pair-default-inhibit' might not be defined at runtime.
make: *** [Makefile:69: build-26.1/haskell-mode.elc] Error 1
`

**Comment by purcell** [comment] 2019-11-14 07:29
Do you have the very latest version from git? Otherwise this looks like a duplicate of https://github.com/haskell/haskell-mode/issues/1682.

**Closed** 2019-11-19 01:38 UTC
