### ISSUE TITLE
Completion function hangs in REPL in multi-line editing mode

### ISSUE THREAD

**Issue by geraldus** [haskell/haskell-mode#1173] opened 2016-02-22 01:41 UTC
Steps to reproduce:
+ start REPL process
+ enter multi-line edit mode, e.g. type `:{` and hit <kbd>RET</kbd>
+ type something that could be auto-completed
+ invoke `complete-symbol` function <kbd>C-M-i</kbd> _(or in case when `company-mode` enabled issue appears immediately)_

**Comment by fice-t** [comment] 2016-02-22 03:44
Seems to be a duplicate of #871. This bit me as well.

Everything seems to be screwed in multi-line mode though. One thing that would be really nice is automatic indentation inside of it. 
Perhaps there should be one big issue for REPL multi-line mode?

**Comment by gracjan** [comment] 2016-02-22 06:43
Dupe of #871. Please discuss this issue there.

**Closed by gracjan** 2016-02-22 06:43 UTC
