### ISSUE TITLE
inferior-haskell-mode documentation is wrong, doesn't explain how to start it

### ISSUE THREAD

**Issue by ian-kelling** [haskell/haskell-mode#327] opened 2014-08-29 05:39 UTC
The bindings it describes don't exist. Instead, they are mostly, except C-c C-b, bound to a function which says:

"haskell-mode-enable-process-minor-mode: You tried to do an interaction command, but an interaction mode has not been enabled yet.

Run M-x describe-variable haskell-mode-hook for a list of such modes."

But actually doing that just shows me a blank hook variable

**Comment by gracjan** [comment] 2015-03-27 20:20
I'll close this as a duplicate of #522 where you can find more information.

Basically some Emacsen do not show documentation for hook variables so all docs from there need to be moved to mode description.

**Closed by gracjan** 2015-03-27 20:20 UTC
